# ####################################################################

#  Created by Genus(TM) Synthesis Solution 20.11-s111_1 on Wed Mar 25 16:16:10 IST 2026

# ####################################################################

set sdc_version 2.0

set_units -capacitance 1000fF
set_units -time 1000ps

# Set the current design
current_design bfv_top

create_clock -name "clk" -period 10.0 -waveform {0.0 5.0} [get_ports clk]
set_clock_transition 0.2 [get_clocks clk]
set_load -pin_load 2.0 [get_ports done]
set_load -pin_load 2.0 [get_ports {state_out[3]}]
set_load -pin_load 2.0 [get_ports {state_out[2]}]
set_load -pin_load 2.0 [get_ports {state_out[1]}]
set_load -pin_load 2.0 [get_ports {state_out[0]}]
set_load -pin_load 2.0 [get_ports {dbg_pk1[13]}]
set_load -pin_load 2.0 [get_ports {dbg_pk1[12]}]
set_load -pin_load 2.0 [get_ports {dbg_pk1[11]}]
set_load -pin_load 2.0 [get_ports {dbg_pk1[10]}]
set_load -pin_load 2.0 [get_ports {dbg_pk1[9]}]
set_load -pin_load 2.0 [get_ports {dbg_pk1[8]}]
set_load -pin_load 2.0 [get_ports {dbg_pk1[7]}]
set_load -pin_load 2.0 [get_ports {dbg_pk1[6]}]
set_load -pin_load 2.0 [get_ports {dbg_pk1[5]}]
set_load -pin_load 2.0 [get_ports {dbg_pk1[4]}]
set_load -pin_load 2.0 [get_ports {dbg_pk1[3]}]
set_load -pin_load 2.0 [get_ports {dbg_pk1[2]}]
set_load -pin_load 2.0 [get_ports {dbg_pk1[1]}]
set_load -pin_load 2.0 [get_ports {dbg_pk1[0]}]
set_load -pin_load 2.0 [get_ports {dbg_pk2[13]}]
set_load -pin_load 2.0 [get_ports {dbg_pk2[12]}]
set_load -pin_load 2.0 [get_ports {dbg_pk2[11]}]
set_load -pin_load 2.0 [get_ports {dbg_pk2[10]}]
set_load -pin_load 2.0 [get_ports {dbg_pk2[9]}]
set_load -pin_load 2.0 [get_ports {dbg_pk2[8]}]
set_load -pin_load 2.0 [get_ports {dbg_pk2[7]}]
set_load -pin_load 2.0 [get_ports {dbg_pk2[6]}]
set_load -pin_load 2.0 [get_ports {dbg_pk2[5]}]
set_load -pin_load 2.0 [get_ports {dbg_pk2[4]}]
set_load -pin_load 2.0 [get_ports {dbg_pk2[3]}]
set_load -pin_load 2.0 [get_ports {dbg_pk2[2]}]
set_load -pin_load 2.0 [get_ports {dbg_pk2[1]}]
set_load -pin_load 2.0 [get_ports {dbg_pk2[0]}]
set_load -pin_load 2.0 [get_ports {dbg_pix_cnt[11]}]
set_load -pin_load 2.0 [get_ports {dbg_pix_cnt[10]}]
set_load -pin_load 2.0 [get_ports {dbg_pix_cnt[9]}]
set_load -pin_load 2.0 [get_ports {dbg_pix_cnt[8]}]
set_load -pin_load 2.0 [get_ports {dbg_pix_cnt[7]}]
set_load -pin_load 2.0 [get_ports {dbg_pix_cnt[6]}]
set_load -pin_load 2.0 [get_ports {dbg_pix_cnt[5]}]
set_load -pin_load 2.0 [get_ports {dbg_pix_cnt[4]}]
set_load -pin_load 2.0 [get_ports {dbg_pix_cnt[3]}]
set_load -pin_load 2.0 [get_ports {dbg_pix_cnt[2]}]
set_load -pin_load 2.0 [get_ports {dbg_pix_cnt[1]}]
set_load -pin_load 2.0 [get_ports {dbg_pix_cnt[0]}]
set_clock_gating_check -setup 0.0 
set_input_delay -clock [get_clocks clk] -add_delay -max 0.5 [get_ports rst_n]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.5 [get_ports start]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.5 [get_ports {sk[13]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.5 [get_ports {sk[12]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.5 [get_ports {sk[11]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.5 [get_ports {sk[10]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.5 [get_ports {sk[9]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.5 [get_ports {sk[8]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.5 [get_ports {sk[7]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.5 [get_ports {sk[6]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.5 [get_ports {sk[5]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.5 [get_ports {sk[4]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.5 [get_ports {sk[3]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.5 [get_ports {sk[2]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.5 [get_ports {sk[1]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.5 [get_ports {sk[0]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.5 [get_ports {a_key[13]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.5 [get_ports {a_key[12]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.5 [get_ports {a_key[11]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.5 [get_ports {a_key[10]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.5 [get_ports {a_key[9]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.5 [get_ports {a_key[8]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.5 [get_ports {a_key[7]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.5 [get_ports {a_key[6]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.5 [get_ports {a_key[5]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.5 [get_ports {a_key[4]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.5 [get_ports {a_key[3]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.5 [get_ports {a_key[2]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.5 [get_ports {a_key[1]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.5 [get_ports {a_key[0]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.5 [get_ports {e_key[13]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.5 [get_ports {e_key[12]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.5 [get_ports {e_key[11]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.5 [get_ports {e_key[10]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.5 [get_ports {e_key[9]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.5 [get_ports {e_key[8]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.5 [get_ports {e_key[7]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.5 [get_ports {e_key[6]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.5 [get_ports {e_key[5]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.5 [get_ports {e_key[4]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.5 [get_ports {e_key[3]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.5 [get_ports {e_key[2]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.5 [get_ports {e_key[1]}]
set_input_delay -clock [get_clocks clk] -add_delay -max 0.5 [get_ports {e_key[0]}]
set_input_delay -clock [get_clocks clk] -add_delay -min 0.1 [get_ports rst_n]
set_input_delay -clock [get_clocks clk] -add_delay -min 0.1 [get_ports start]
set_input_delay -clock [get_clocks clk] -add_delay -min 0.1 [get_ports {sk[13]}]
set_input_delay -clock [get_clocks clk] -add_delay -min 0.1 [get_ports {sk[12]}]
set_input_delay -clock [get_clocks clk] -add_delay -min 0.1 [get_ports {sk[11]}]
set_input_delay -clock [get_clocks clk] -add_delay -min 0.1 [get_ports {sk[10]}]
set_input_delay -clock [get_clocks clk] -add_delay -min 0.1 [get_ports {sk[9]}]
set_input_delay -clock [get_clocks clk] -add_delay -min 0.1 [get_ports {sk[8]}]
set_input_delay -clock [get_clocks clk] -add_delay -min 0.1 [get_ports {sk[7]}]
set_input_delay -clock [get_clocks clk] -add_delay -min 0.1 [get_ports {sk[6]}]
set_input_delay -clock [get_clocks clk] -add_delay -min 0.1 [get_ports {sk[5]}]
set_input_delay -clock [get_clocks clk] -add_delay -min 0.1 [get_ports {sk[4]}]
set_input_delay -clock [get_clocks clk] -add_delay -min 0.1 [get_ports {sk[3]}]
set_input_delay -clock [get_clocks clk] -add_delay -min 0.1 [get_ports {sk[2]}]
set_input_delay -clock [get_clocks clk] -add_delay -min 0.1 [get_ports {sk[1]}]
set_input_delay -clock [get_clocks clk] -add_delay -min 0.1 [get_ports {sk[0]}]
set_input_delay -clock [get_clocks clk] -add_delay -min 0.1 [get_ports {a_key[13]}]
set_input_delay -clock [get_clocks clk] -add_delay -min 0.1 [get_ports {a_key[12]}]
set_input_delay -clock [get_clocks clk] -add_delay -min 0.1 [get_ports {a_key[11]}]
set_input_delay -clock [get_clocks clk] -add_delay -min 0.1 [get_ports {a_key[10]}]
set_input_delay -clock [get_clocks clk] -add_delay -min 0.1 [get_ports {a_key[9]}]
set_input_delay -clock [get_clocks clk] -add_delay -min 0.1 [get_ports {a_key[8]}]
set_input_delay -clock [get_clocks clk] -add_delay -min 0.1 [get_ports {a_key[7]}]
set_input_delay -clock [get_clocks clk] -add_delay -min 0.1 [get_ports {a_key[6]}]
set_input_delay -clock [get_clocks clk] -add_delay -min 0.1 [get_ports {a_key[5]}]
set_input_delay -clock [get_clocks clk] -add_delay -min 0.1 [get_ports {a_key[4]}]
set_input_delay -clock [get_clocks clk] -add_delay -min 0.1 [get_ports {a_key[3]}]
set_input_delay -clock [get_clocks clk] -add_delay -min 0.1 [get_ports {a_key[2]}]
set_input_delay -clock [get_clocks clk] -add_delay -min 0.1 [get_ports {a_key[1]}]
set_input_delay -clock [get_clocks clk] -add_delay -min 0.1 [get_ports {a_key[0]}]
set_input_delay -clock [get_clocks clk] -add_delay -min 0.1 [get_ports {e_key[13]}]
set_input_delay -clock [get_clocks clk] -add_delay -min 0.1 [get_ports {e_key[12]}]
set_input_delay -clock [get_clocks clk] -add_delay -min 0.1 [get_ports {e_key[11]}]
set_input_delay -clock [get_clocks clk] -add_delay -min 0.1 [get_ports {e_key[10]}]
set_input_delay -clock [get_clocks clk] -add_delay -min 0.1 [get_ports {e_key[9]}]
set_input_delay -clock [get_clocks clk] -add_delay -min 0.1 [get_ports {e_key[8]}]
set_input_delay -clock [get_clocks clk] -add_delay -min 0.1 [get_ports {e_key[7]}]
set_input_delay -clock [get_clocks clk] -add_delay -min 0.1 [get_ports {e_key[6]}]
set_input_delay -clock [get_clocks clk] -add_delay -min 0.1 [get_ports {e_key[5]}]
set_input_delay -clock [get_clocks clk] -add_delay -min 0.1 [get_ports {e_key[4]}]
set_input_delay -clock [get_clocks clk] -add_delay -min 0.1 [get_ports {e_key[3]}]
set_input_delay -clock [get_clocks clk] -add_delay -min 0.1 [get_ports {e_key[2]}]
set_input_delay -clock [get_clocks clk] -add_delay -min 0.1 [get_ports {e_key[1]}]
set_input_delay -clock [get_clocks clk] -add_delay -min 0.1 [get_ports {e_key[0]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 0.5 [get_ports done]
set_output_delay -clock [get_clocks clk] -add_delay -max 0.5 [get_ports {state_out[3]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 0.5 [get_ports {state_out[2]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 0.5 [get_ports {state_out[1]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 0.5 [get_ports {state_out[0]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 0.5 [get_ports {dbg_pk1[13]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 0.5 [get_ports {dbg_pk1[12]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 0.5 [get_ports {dbg_pk1[11]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 0.5 [get_ports {dbg_pk1[10]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 0.5 [get_ports {dbg_pk1[9]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 0.5 [get_ports {dbg_pk1[8]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 0.5 [get_ports {dbg_pk1[7]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 0.5 [get_ports {dbg_pk1[6]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 0.5 [get_ports {dbg_pk1[5]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 0.5 [get_ports {dbg_pk1[4]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 0.5 [get_ports {dbg_pk1[3]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 0.5 [get_ports {dbg_pk1[2]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 0.5 [get_ports {dbg_pk1[1]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 0.5 [get_ports {dbg_pk1[0]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 0.5 [get_ports {dbg_pk2[13]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 0.5 [get_ports {dbg_pk2[12]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 0.5 [get_ports {dbg_pk2[11]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 0.5 [get_ports {dbg_pk2[10]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 0.5 [get_ports {dbg_pk2[9]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 0.5 [get_ports {dbg_pk2[8]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 0.5 [get_ports {dbg_pk2[7]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 0.5 [get_ports {dbg_pk2[6]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 0.5 [get_ports {dbg_pk2[5]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 0.5 [get_ports {dbg_pk2[4]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 0.5 [get_ports {dbg_pk2[3]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 0.5 [get_ports {dbg_pk2[2]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 0.5 [get_ports {dbg_pk2[1]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 0.5 [get_ports {dbg_pk2[0]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 0.5 [get_ports {dbg_pix_cnt[11]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 0.5 [get_ports {dbg_pix_cnt[10]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 0.5 [get_ports {dbg_pix_cnt[9]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 0.5 [get_ports {dbg_pix_cnt[8]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 0.5 [get_ports {dbg_pix_cnt[7]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 0.5 [get_ports {dbg_pix_cnt[6]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 0.5 [get_ports {dbg_pix_cnt[5]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 0.5 [get_ports {dbg_pix_cnt[4]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 0.5 [get_ports {dbg_pix_cnt[3]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 0.5 [get_ports {dbg_pix_cnt[2]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 0.5 [get_ports {dbg_pix_cnt[1]}]
set_output_delay -clock [get_clocks clk] -add_delay -max 0.5 [get_ports {dbg_pix_cnt[0]}]
set_output_delay -clock [get_clocks clk] -add_delay -min 0.1 [get_ports done]
set_output_delay -clock [get_clocks clk] -add_delay -min 0.1 [get_ports {state_out[3]}]
set_output_delay -clock [get_clocks clk] -add_delay -min 0.1 [get_ports {state_out[2]}]
set_output_delay -clock [get_clocks clk] -add_delay -min 0.1 [get_ports {state_out[1]}]
set_output_delay -clock [get_clocks clk] -add_delay -min 0.1 [get_ports {state_out[0]}]
set_output_delay -clock [get_clocks clk] -add_delay -min 0.1 [get_ports {dbg_pk1[13]}]
set_output_delay -clock [get_clocks clk] -add_delay -min 0.1 [get_ports {dbg_pk1[12]}]
set_output_delay -clock [get_clocks clk] -add_delay -min 0.1 [get_ports {dbg_pk1[11]}]
set_output_delay -clock [get_clocks clk] -add_delay -min 0.1 [get_ports {dbg_pk1[10]}]
set_output_delay -clock [get_clocks clk] -add_delay -min 0.1 [get_ports {dbg_pk1[9]}]
set_output_delay -clock [get_clocks clk] -add_delay -min 0.1 [get_ports {dbg_pk1[8]}]
set_output_delay -clock [get_clocks clk] -add_delay -min 0.1 [get_ports {dbg_pk1[7]}]
set_output_delay -clock [get_clocks clk] -add_delay -min 0.1 [get_ports {dbg_pk1[6]}]
set_output_delay -clock [get_clocks clk] -add_delay -min 0.1 [get_ports {dbg_pk1[5]}]
set_output_delay -clock [get_clocks clk] -add_delay -min 0.1 [get_ports {dbg_pk1[4]}]
set_output_delay -clock [get_clocks clk] -add_delay -min 0.1 [get_ports {dbg_pk1[3]}]
set_output_delay -clock [get_clocks clk] -add_delay -min 0.1 [get_ports {dbg_pk1[2]}]
set_output_delay -clock [get_clocks clk] -add_delay -min 0.1 [get_ports {dbg_pk1[1]}]
set_output_delay -clock [get_clocks clk] -add_delay -min 0.1 [get_ports {dbg_pk1[0]}]
set_output_delay -clock [get_clocks clk] -add_delay -min 0.1 [get_ports {dbg_pk2[13]}]
set_output_delay -clock [get_clocks clk] -add_delay -min 0.1 [get_ports {dbg_pk2[12]}]
set_output_delay -clock [get_clocks clk] -add_delay -min 0.1 [get_ports {dbg_pk2[11]}]
set_output_delay -clock [get_clocks clk] -add_delay -min 0.1 [get_ports {dbg_pk2[10]}]
set_output_delay -clock [get_clocks clk] -add_delay -min 0.1 [get_ports {dbg_pk2[9]}]
set_output_delay -clock [get_clocks clk] -add_delay -min 0.1 [get_ports {dbg_pk2[8]}]
set_output_delay -clock [get_clocks clk] -add_delay -min 0.1 [get_ports {dbg_pk2[7]}]
set_output_delay -clock [get_clocks clk] -add_delay -min 0.1 [get_ports {dbg_pk2[6]}]
set_output_delay -clock [get_clocks clk] -add_delay -min 0.1 [get_ports {dbg_pk2[5]}]
set_output_delay -clock [get_clocks clk] -add_delay -min 0.1 [get_ports {dbg_pk2[4]}]
set_output_delay -clock [get_clocks clk] -add_delay -min 0.1 [get_ports {dbg_pk2[3]}]
set_output_delay -clock [get_clocks clk] -add_delay -min 0.1 [get_ports {dbg_pk2[2]}]
set_output_delay -clock [get_clocks clk] -add_delay -min 0.1 [get_ports {dbg_pk2[1]}]
set_output_delay -clock [get_clocks clk] -add_delay -min 0.1 [get_ports {dbg_pk2[0]}]
set_output_delay -clock [get_clocks clk] -add_delay -min 0.1 [get_ports {dbg_pix_cnt[11]}]
set_output_delay -clock [get_clocks clk] -add_delay -min 0.1 [get_ports {dbg_pix_cnt[10]}]
set_output_delay -clock [get_clocks clk] -add_delay -min 0.1 [get_ports {dbg_pix_cnt[9]}]
set_output_delay -clock [get_clocks clk] -add_delay -min 0.1 [get_ports {dbg_pix_cnt[8]}]
set_output_delay -clock [get_clocks clk] -add_delay -min 0.1 [get_ports {dbg_pix_cnt[7]}]
set_output_delay -clock [get_clocks clk] -add_delay -min 0.1 [get_ports {dbg_pix_cnt[6]}]
set_output_delay -clock [get_clocks clk] -add_delay -min 0.1 [get_ports {dbg_pix_cnt[5]}]
set_output_delay -clock [get_clocks clk] -add_delay -min 0.1 [get_ports {dbg_pix_cnt[4]}]
set_output_delay -clock [get_clocks clk] -add_delay -min 0.1 [get_ports {dbg_pix_cnt[3]}]
set_output_delay -clock [get_clocks clk] -add_delay -min 0.1 [get_ports {dbg_pix_cnt[2]}]
set_output_delay -clock [get_clocks clk] -add_delay -min 0.1 [get_ports {dbg_pix_cnt[1]}]
set_output_delay -clock [get_clocks clk] -add_delay -min 0.1 [get_ports {dbg_pix_cnt[0]}]
set_max_leakage_power 0.0
set_max_dynamic_power 0.0
set_input_transition 0.5 [get_ports clk]
set_input_transition 0.5 [get_ports rst_n]
set_input_transition 0.5 [get_ports start]
set_input_transition 0.5 [get_ports {sk[13]}]
set_input_transition 0.5 [get_ports {sk[12]}]
set_input_transition 0.5 [get_ports {sk[11]}]
set_input_transition 0.5 [get_ports {sk[10]}]
set_input_transition 0.5 [get_ports {sk[9]}]
set_input_transition 0.5 [get_ports {sk[8]}]
set_input_transition 0.5 [get_ports {sk[7]}]
set_input_transition 0.5 [get_ports {sk[6]}]
set_input_transition 0.5 [get_ports {sk[5]}]
set_input_transition 0.5 [get_ports {sk[4]}]
set_input_transition 0.5 [get_ports {sk[3]}]
set_input_transition 0.5 [get_ports {sk[2]}]
set_input_transition 0.5 [get_ports {sk[1]}]
set_input_transition 0.5 [get_ports {sk[0]}]
set_input_transition 0.5 [get_ports {a_key[13]}]
set_input_transition 0.5 [get_ports {a_key[12]}]
set_input_transition 0.5 [get_ports {a_key[11]}]
set_input_transition 0.5 [get_ports {a_key[10]}]
set_input_transition 0.5 [get_ports {a_key[9]}]
set_input_transition 0.5 [get_ports {a_key[8]}]
set_input_transition 0.5 [get_ports {a_key[7]}]
set_input_transition 0.5 [get_ports {a_key[6]}]
set_input_transition 0.5 [get_ports {a_key[5]}]
set_input_transition 0.5 [get_ports {a_key[4]}]
set_input_transition 0.5 [get_ports {a_key[3]}]
set_input_transition 0.5 [get_ports {a_key[2]}]
set_input_transition 0.5 [get_ports {a_key[1]}]
set_input_transition 0.5 [get_ports {a_key[0]}]
set_input_transition 0.5 [get_ports {e_key[13]}]
set_input_transition 0.5 [get_ports {e_key[12]}]
set_input_transition 0.5 [get_ports {e_key[11]}]
set_input_transition 0.5 [get_ports {e_key[10]}]
set_input_transition 0.5 [get_ports {e_key[9]}]
set_input_transition 0.5 [get_ports {e_key[8]}]
set_input_transition 0.5 [get_ports {e_key[7]}]
set_input_transition 0.5 [get_ports {e_key[6]}]
set_input_transition 0.5 [get_ports {e_key[5]}]
set_input_transition 0.5 [get_ports {e_key[4]}]
set_input_transition 0.5 [get_ports {e_key[3]}]
set_input_transition 0.5 [get_ports {e_key[2]}]
set_input_transition 0.5 [get_ports {e_key[1]}]
set_input_transition 0.5 [get_ports {e_key[0]}]
set_wire_load_mode "enclosed"
set_clock_uncertainty -setup 0.2 [get_clocks clk]
set_clock_uncertainty -hold 0.1 [get_clocks clk]
