
//input ports
add mapped point clk clk -type PI PI
add mapped point rst_n rst_n -type PI PI
add mapped point start start -type PI PI
add mapped point sk[13] sk[13] -type PI PI
add mapped point sk[12] sk[12] -type PI PI
add mapped point sk[11] sk[11] -type PI PI
add mapped point sk[10] sk[10] -type PI PI
add mapped point sk[9] sk[9] -type PI PI
add mapped point sk[8] sk[8] -type PI PI
add mapped point sk[7] sk[7] -type PI PI
add mapped point sk[6] sk[6] -type PI PI
add mapped point sk[5] sk[5] -type PI PI
add mapped point sk[4] sk[4] -type PI PI
add mapped point sk[3] sk[3] -type PI PI
add mapped point sk[2] sk[2] -type PI PI
add mapped point sk[1] sk[1] -type PI PI
add mapped point sk[0] sk[0] -type PI PI
add mapped point a_key[13] a_key[13] -type PI PI
add mapped point a_key[12] a_key[12] -type PI PI
add mapped point a_key[11] a_key[11] -type PI PI
add mapped point a_key[10] a_key[10] -type PI PI
add mapped point a_key[9] a_key[9] -type PI PI
add mapped point a_key[8] a_key[8] -type PI PI
add mapped point a_key[7] a_key[7] -type PI PI
add mapped point a_key[6] a_key[6] -type PI PI
add mapped point a_key[5] a_key[5] -type PI PI
add mapped point a_key[4] a_key[4] -type PI PI
add mapped point a_key[3] a_key[3] -type PI PI
add mapped point a_key[2] a_key[2] -type PI PI
add mapped point a_key[1] a_key[1] -type PI PI
add mapped point a_key[0] a_key[0] -type PI PI
add mapped point e_key[13] e_key[13] -type PI PI
add mapped point e_key[12] e_key[12] -type PI PI
add mapped point e_key[11] e_key[11] -type PI PI
add mapped point e_key[10] e_key[10] -type PI PI
add mapped point e_key[9] e_key[9] -type PI PI
add mapped point e_key[8] e_key[8] -type PI PI
add mapped point e_key[7] e_key[7] -type PI PI
add mapped point e_key[6] e_key[6] -type PI PI
add mapped point e_key[5] e_key[5] -type PI PI
add mapped point e_key[4] e_key[4] -type PI PI
add mapped point e_key[3] e_key[3] -type PI PI
add mapped point e_key[2] e_key[2] -type PI PI
add mapped point e_key[1] e_key[1] -type PI PI
add mapped point e_key[0] e_key[0] -type PI PI

//output ports
add mapped point done done -type PO PO
add mapped point state_out[3] state_out[3] -type PO PO
add mapped point state_out[2] state_out[2] -type PO PO
add mapped point state_out[1] state_out[1] -type PO PO
add mapped point state_out[0] state_out[0] -type PO PO
add mapped point dbg_pk1[13] dbg_pk1[13] -type PO PO
add mapped point dbg_pk1[12] dbg_pk1[12] -type PO PO
add mapped point dbg_pk1[11] dbg_pk1[11] -type PO PO
add mapped point dbg_pk1[10] dbg_pk1[10] -type PO PO
add mapped point dbg_pk1[9] dbg_pk1[9] -type PO PO
add mapped point dbg_pk1[8] dbg_pk1[8] -type PO PO
add mapped point dbg_pk1[7] dbg_pk1[7] -type PO PO
add mapped point dbg_pk1[6] dbg_pk1[6] -type PO PO
add mapped point dbg_pk1[5] dbg_pk1[5] -type PO PO
add mapped point dbg_pk1[4] dbg_pk1[4] -type PO PO
add mapped point dbg_pk1[3] dbg_pk1[3] -type PO PO
add mapped point dbg_pk1[2] dbg_pk1[2] -type PO PO
add mapped point dbg_pk1[1] dbg_pk1[1] -type PO PO
add mapped point dbg_pk1[0] dbg_pk1[0] -type PO PO
add mapped point dbg_pk2[13] dbg_pk2[13] -type PO PO
add mapped point dbg_pk2[12] dbg_pk2[12] -type PO PO
add mapped point dbg_pk2[11] dbg_pk2[11] -type PO PO
add mapped point dbg_pk2[10] dbg_pk2[10] -type PO PO
add mapped point dbg_pk2[9] dbg_pk2[9] -type PO PO
add mapped point dbg_pk2[8] dbg_pk2[8] -type PO PO
add mapped point dbg_pk2[7] dbg_pk2[7] -type PO PO
add mapped point dbg_pk2[6] dbg_pk2[6] -type PO PO
add mapped point dbg_pk2[5] dbg_pk2[5] -type PO PO
add mapped point dbg_pk2[4] dbg_pk2[4] -type PO PO
add mapped point dbg_pk2[3] dbg_pk2[3] -type PO PO
add mapped point dbg_pk2[2] dbg_pk2[2] -type PO PO
add mapped point dbg_pk2[1] dbg_pk2[1] -type PO PO
add mapped point dbg_pk2[0] dbg_pk2[0] -type PO PO
add mapped point dbg_pix_cnt[11] dbg_pix_cnt[11] -type PO PO
add mapped point dbg_pix_cnt[10] dbg_pix_cnt[10] -type PO PO
add mapped point dbg_pix_cnt[9] dbg_pix_cnt[9] -type PO PO
add mapped point dbg_pix_cnt[8] dbg_pix_cnt[8] -type PO PO
add mapped point dbg_pix_cnt[7] dbg_pix_cnt[7] -type PO PO
add mapped point dbg_pix_cnt[6] dbg_pix_cnt[6] -type PO PO
add mapped point dbg_pix_cnt[5] dbg_pix_cnt[5] -type PO PO
add mapped point dbg_pix_cnt[4] dbg_pix_cnt[4] -type PO PO
add mapped point dbg_pix_cnt[3] dbg_pix_cnt[3] -type PO PO
add mapped point dbg_pix_cnt[2] dbg_pix_cnt[2] -type PO PO
add mapped point dbg_pix_cnt[1] dbg_pix_cnt[1] -type PO PO
add mapped point dbg_pix_cnt[0] dbg_pix_cnt[0] -type PO PO

//inout ports




//Sequential Pins
add mapped point state_out[3]/q state_out_reg[3]/Q  -type DFF DFF
add mapped point state_out[2]/q state_out_reg[2]/Q  -type DFF DFF
add mapped point state_out[0]/q state_out_reg[0]/Q  -type DFF DFF
add mapped point state_out[1]/q state_out_reg[1]/Q  -type DFF DFF
add mapped point dbg_pix_cnt[0]/q dbg_pix_cnt_reg[0]/Q  -type DFF DFF
add mapped point dbg_pix_cnt[1]/q dbg_pix_cnt_reg[1]/Q  -type DFF DFF
add mapped point dbg_pix_cnt[2]/q dbg_pix_cnt_reg[2]/Q  -type DFF DFF
add mapped point dbg_pix_cnt[3]/q dbg_pix_cnt_reg[3]/Q  -type DFF DFF
add mapped point dbg_pix_cnt[4]/q dbg_pix_cnt_reg[4]/Q  -type DFF DFF
add mapped point dbg_pix_cnt[5]/q dbg_pix_cnt_reg[5]/Q  -type DFF DFF
add mapped point dbg_pix_cnt[6]/q dbg_pix_cnt_reg[6]/Q  -type DFF DFF
add mapped point dbg_pix_cnt[7]/q dbg_pix_cnt_reg[7]/Q  -type DFF DFF
add mapped point dbg_pix_cnt[8]/q dbg_pix_cnt_reg[8]/Q  -type DFF DFF
add mapped point dbg_pix_cnt[9]/q dbg_pix_cnt_reg[9]/Q  -type DFF DFF
add mapped point dbg_pix_cnt[10]/q dbg_pix_cnt_reg[10]/Q  -type DFF DFF
add mapped point dbg_pix_cnt[11]/q dbg_pix_cnt_reg[11]/Q  -type DFF DFF
add mapped point dbg_pk1[0]/q dbg_pk1_reg[0]/Q  -type DFF DFF
add mapped point dbg_pk1[1]/q dbg_pk1_reg[1]/Q  -type DFF DFF
add mapped point dbg_pk1[2]/q dbg_pk1_reg[2]/Q  -type DFF DFF
add mapped point dbg_pk1[3]/q dbg_pk1_reg[3]/Q  -type DFF DFF
add mapped point dbg_pk1[4]/q dbg_pk1_reg[4]/Q  -type DFF DFF
add mapped point dbg_pk1[5]/q dbg_pk1_reg[5]/Q  -type DFF DFF
add mapped point dbg_pk1[6]/q dbg_pk1_reg[6]/Q  -type DFF DFF
add mapped point dbg_pk1[7]/q dbg_pk1_reg[7]/Q  -type DFF DFF
add mapped point dbg_pk1[8]/q dbg_pk1_reg[8]/Q  -type DFF DFF
add mapped point dbg_pk1[9]/q dbg_pk1_reg[9]/Q  -type DFF DFF
add mapped point dbg_pk1[10]/q dbg_pk1_reg[10]/Q  -type DFF DFF
add mapped point dbg_pk1[11]/q dbg_pk1_reg[11]/Q  -type DFF DFF
add mapped point dbg_pk1[12]/q dbg_pk1_reg[12]/Q  -type DFF DFF
add mapped point dbg_pk1[13]/q dbg_pk1_reg[13]/Q  -type DFF DFF
add mapped point dbg_pk2[0]/q dbg_pk2_reg[0]/Q  -type DFF DFF
add mapped point dbg_pk2[1]/q dbg_pk2_reg[1]/Q  -type DFF DFF
add mapped point dbg_pk2[2]/q dbg_pk2_reg[2]/Q  -type DFF DFF
add mapped point dbg_pk2[3]/q dbg_pk2_reg[3]/Q  -type DFF DFF
add mapped point dbg_pk2[4]/q dbg_pk2_reg[4]/Q  -type DFF DFF
add mapped point dbg_pk2[5]/q dbg_pk2_reg[5]/Q  -type DFF DFF
add mapped point dbg_pk2[6]/q dbg_pk2_reg[6]/Q  -type DFF DFF
add mapped point dbg_pk2[7]/q dbg_pk2_reg[7]/Q  -type DFF DFF
add mapped point dbg_pk2[8]/q dbg_pk2_reg[8]/Q  -type DFF DFF
add mapped point dbg_pk2[9]/q dbg_pk2_reg[9]/Q  -type DFF DFF
add mapped point dbg_pk2[10]/q dbg_pk2_reg[10]/Q  -type DFF DFF
add mapped point dbg_pk2[11]/q dbg_pk2_reg[11]/Q  -type DFF DFF
add mapped point dbg_pk2[12]/q dbg_pk2_reg[12]/Q  -type DFF DFF
add mapped point dbg_pk2[13]/q dbg_pk2_reg[13]/Q  -type DFF DFF
add mapped point done/q done_reg/Q  -type DFF DFF
add mapped point pix_cnt[0]/q pix_cnt_reg[0]/Q  -type DFF DFF
add mapped point pix_cnt[1]/q pix_cnt_reg[1]/Q  -type DFF DFF
add mapped point pix_cnt[2]/q pix_cnt_reg[2]/Q  -type DFF DFF
add mapped point pix_cnt[3]/q pix_cnt_reg[3]/Q  -type DFF DFF
add mapped point pix_cnt[4]/q pix_cnt_reg[4]/Q  -type DFF DFF
add mapped point pix_cnt[5]/q pix_cnt_reg[5]/Q  -type DFF DFF
add mapped point pix_cnt[6]/q pix_cnt_reg[6]/Q  -type DFF DFF
add mapped point pix_cnt[7]/q pix_cnt_reg[7]/Q  -type DFF DFF
add mapped point pix_cnt[8]/q pix_cnt_reg[8]/Q  -type DFF DFF
add mapped point pix_cnt[9]/q pix_cnt_reg[9]/Q  -type DFF DFF
add mapped point pix_cnt[10]/q pix_cnt_reg[10]/Q  -type DFF DFF
add mapped point pix_cnt[11]/q pix_cnt_reg[11]/Q  -type DFF DFF
add mapped point state[0]/q state_reg[0]/Q  -type DFF DFF
add mapped point state[1]/q state_reg[1]/Q  -type DFF DFF
add mapped point state[2]/q state_reg[2]/Q  -type DFF DFF
add mapped point state[3]/q state_reg[3]/Q  -type DFF DFF
add mapped point u_keygen/u_mult_ask/product_pipe[14]/q u_keygen_u_mult_ask_product_pipe_reg[14]/Q  -type DFF DFF
add mapped point u_keygen/u_mult_ask/product_pipe[1]/q u_keygen_u_mult_ask_product_pipe_reg[1]/Q  -type DFF DFF
add mapped point u_keygen/u_mult_ask/result[12]/q u_keygen_u_mult_ask_result_reg[12]/Q  -type DFF DFF
add mapped point u_keygen/u_mult_ask/result[11]/q u_keygen_u_mult_ask_result_reg[11]/Q  -type DFF DFF
add mapped point u_keygen/u_mult_ask/result[13]/q u_keygen_u_mult_ask_result_reg[13]/Q  -type DFF DFF
add mapped point u_keygen/u_mult_ask/product_pipe[2]/q u_keygen_u_mult_ask_product_pipe_reg[2]/Q  -type DFF DFF
add mapped point u_keygen/u_mult_ask/product_pipe[3]/q u_keygen_u_mult_ask_product_pipe_reg[3]/Q  -type DFF DFF
add mapped point u_keygen/u_mult_ask/result[7]/q u_keygen_u_mult_ask_result_reg[7]/Q  -type DFF DFF
add mapped point u_keygen/u_mult_ask/product_pipe[4]/q u_keygen_u_mult_ask_product_pipe_reg[4]/Q  -type DFF DFF
add mapped point u_keygen/u_mult_ask/product_pipe[5]/q u_keygen_u_mult_ask_product_pipe_reg[5]/Q  -type DFF DFF
add mapped point u_keygen/u_mult_ask/product_pipe[6]/q u_keygen_u_mult_ask_product_pipe_reg[6]/Q  -type DFF DFF
add mapped point u_keygen/u_mult_ask/result[3]/q u_keygen_u_mult_ask_result_reg[3]/Q  -type DFF DFF
add mapped point u_keygen/u_mult_ask/product_pipe[7]/q u_keygen_u_mult_ask_product_pipe_reg[7]/Q  -type DFF DFF
add mapped point u_keygen/u_mult_ask/product_pipe[8]/q u_keygen_u_mult_ask_product_pipe_reg[8]/Q  -type DFF DFF
add mapped point u_keygen/u_mult_ask/product_pipe[9]/q u_keygen_u_mult_ask_product_pipe_reg[9]/Q  -type DFF DFF
add mapped point u_keygen/u_mult_ask/product_pipe[10]/q u_keygen_u_mult_ask_product_pipe_reg[10]/Q  -type DFF DFF
add mapped point u_keygen/u_mult_ask/product_pipe[11]/q u_keygen_u_mult_ask_product_pipe_reg[11]/Q  -type DFF DFF
add mapped point u_keygen/u_mult_ask/product_pipe[12]/q u_keygen_u_mult_ask_product_pipe_reg[12]/Q  -type DFF DFF
add mapped point u_keygen/u_mult_ask/product_pipe[13]/q u_keygen_u_mult_ask_product_pipe_reg[13]/Q  -type DFF DFF
add mapped point u_keygen/u_mult_ask/product_pipe[23]/q u_keygen_u_mult_ask_product_pipe_reg[23]/Q  -type DFF DFF
add mapped point u_keygen/u_mult_ask/product_pipe[0]/q u_keygen_u_mult_ask_product_pipe_reg[0]/Q  -type DFF DFF
add mapped point u_keygen/u_mult_ask/result[10]/q u_keygen_u_mult_ask_result_reg[10]/Q  -type DFF DFF
add mapped point u_keygen/u_mult_ask/product_pipe[16]/q u_keygen_u_mult_ask_product_pipe_reg[16]/Q  -type DFF DFF
add mapped point u_keygen/u_mult_ask/product_pipe[17]/q u_keygen_u_mult_ask_product_pipe_reg[17]/Q  -type DFF DFF
add mapped point u_keygen/u_mult_ask/product_pipe[18]/q u_keygen_u_mult_ask_product_pipe_reg[18]/Q  -type DFF DFF
add mapped point u_keygen/u_mult_ask/product_pipe[19]/q u_keygen_u_mult_ask_product_pipe_reg[19]/Q  -type DFF DFF
add mapped point u_keygen/u_mult_ask/product_pipe[20]/q u_keygen_u_mult_ask_product_pipe_reg[20]/Q  -type DFF DFF
add mapped point u_keygen/u_mult_ask/product_pipe[21]/q u_keygen_u_mult_ask_product_pipe_reg[21]/Q  -type DFF DFF
add mapped point u_keygen/u_mult_ask/product_pipe[22]/q u_keygen_u_mult_ask_product_pipe_reg[22]/Q  -type DFF DFF
add mapped point u_keygen/u_mult_ask/product_pipe[24]/q u_keygen_u_mult_ask_product_pipe_reg[24]/Q  -type DFF DFF
add mapped point u_keygen/u_mult_ask/product_pipe[25]/q u_keygen_u_mult_ask_product_pipe_reg[25]/Q  -type DFF DFF
add mapped point u_keygen/u_mult_ask/product_pipe[26]/q u_keygen_u_mult_ask_product_pipe_reg[26]/Q  -type DFF DFF
add mapped point u_keygen/u_mult_ask/product_pipe[27]/q u_keygen_u_mult_ask_product_pipe_reg[27]/Q  -type DFF DFF
add mapped point u_keygen/u_mult_ask/result[0]/q u_keygen_u_mult_ask_result_reg[0]/Q  -type DFF DFF
add mapped point u_keygen/u_mult_ask/result[1]/q u_keygen_u_mult_ask_result_reg[1]/Q  -type DFF DFF
add mapped point u_keygen/u_mult_ask/result[2]/q u_keygen_u_mult_ask_result_reg[2]/Q  -type DFF DFF
add mapped point u_keygen/u_mult_ask/result[4]/q u_keygen_u_mult_ask_result_reg[4]/Q  -type DFF DFF
add mapped point u_keygen/u_mult_ask/result[5]/q u_keygen_u_mult_ask_result_reg[5]/Q  -type DFF DFF
add mapped point u_keygen/u_mult_ask/result[6]/q u_keygen_u_mult_ask_result_reg[6]/Q  -type DFF DFF
add mapped point u_keygen/u_mult_ask/result[8]/q u_keygen_u_mult_ask_result_reg[8]/Q  -type DFF DFF
add mapped point u_keygen/u_mult_ask/result[9]/q u_keygen_u_mult_ask_result_reg[9]/Q  -type DFF DFF
add mapped point u_keygen/u_mult_ask/product_pipe[15]/q u_keygen_u_mult_ask_product_pipe_reg[15]/Q  -type DFF DFF



//Black Boxes



//Empty Modules as Blackboxes
